### ISSUE TITLE
How to uninstall everything in order to start over

### ISSUE THREAD

**Issue by bmullan** [bketelsen/dlx#31]
During installation  & config of the .05 release I hit at least one failure on Ubuntu 18.04 with SNAP LXD v3.13

> $ devlx template create guitemplate --profile gui --provisioners vscode
> ~ Creating template guitemplate
> ✗ Unable to create template: waiting for container start: Common start logic: Missing source '/tmp/.X11-unix/X1' for disk 'X1'

But then I realized I didn't see any info in the README files about how to completely uninstall and start over?

thanks

**Comment by ChristianBoehm** [comment]
one solution could be, that `lxc image list` and then if there any image listed (maybe it should ubuntu 18.04 LTS amd64 (release)) you could try to delete that image, eg. ` lxc image delete IMAGE_NAME` . Afterwards you need to adapt the gui.yaml according your needs. Like the display variable, network and so on. 

You can find the profiles in `.config/devlx/profiles` I use these 'older' settings, but be aware I have configured a bridged eth device and a mac for my network 

@bketelsen there is a PR open maybe you can have a review look for approving that PR, it could be really nice, with that improved version of devlx, devlx can also remove stucked images with `devlx template ls` and then `devlx template rm IMAGE_NAME` 

```yaml
config:
  environment.DISPLAY: :0
  security.devlxd: false
  raw.idmap: both 1000 1000
  raw.lxc: |
    lxc.apparmor.profile=unconfined
    lxc.mount.auto=proc:rw sys:rw
    lxc.cap.drop=
  security.nesting: "true"
  security.privileged: "true"

description: GUI LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
    hwaddr: xx:xx:xx:xx:xx
  PASocket:
    path: /tmp/.pulse-native
    source: /run/user/1000/pulse/native
    type: disk
  X0:
    bind: container
    connect: unix:@/tmp/.X11-unix/X0
    listen: unix:@/tmp/.X11-unix/X0
    security.gid: "1000"
    security.uid: "1000"
    type: proxy
  mygpu:
    type: gpu
name: gui
used_by:
```
